server:
  port: 5003

spring:
  application:
    name: api-gateway

  main:
    web-application-type: reactive

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/user/**

        - id: salon-service
          uri: lb://SALON-SERVICE
          predicates:
            - Path=/api/salon/**

        - id: category-service
          uri: lb://CATEGORY-SERVICE
          predicates:
            - Path=/api/category/**

        - id: service-offering
          uri: lb://SERVICE-OFFERING
          predicates:
            - Path=/api/serviceoffering/**

        - id: booking-service
          uri: lb://BOOKING-SERVICE
          predicates:
            - Path=/api/booking/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
